site-pedepizza/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  root 'static_pages#home'
  get '/cadastro', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

site-pedepizza/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

site-pedepizza/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
  
end

site-pedepizza/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

site-pedepizza/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :impede_logado, only: [:new]
  before_action :impede_nao_logado, only: [:destroy]

  def new
  end

  def create
      user = User.find_by(email: params[:session][:email])
      if user && user.authenticate(params[:session][:password])
          log_in(user)
          redirect_to user
      else
          render 'new'
      end
  end

  def destroy
      log_out
      redirect_to root_path
  end

  private

  def impede_logado
      if logged_in?
          redirect_to current_user
      end
  end

  def impede_nao_logado
      if !logged_in?
          redirect_to login_path
      end
  end
end

site-pedepizza/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :impede_logado, only: [:home]
    def home
    end

    private

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

site-pedepizza/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :impede_nao_logado, except: [:new, :create]
  before_action :impede_logado, only: [:new]

  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
          log_in @user
          redirect_to @user
      else
          render 'new'
      end
  end

  def index
  end

  def show
      @user=User.find(params[:id])
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def impede_nao_logado
      if !logged_in?
          redirect_to root_path
      end
  end

  def impede_logado
      if logged_in?
          redirect_to current_user
      end
  end
end

site-pedepizza/app/helpers/application_helper.rb
module ApplicationHelper
end

site-pedepizza/app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end
    
    # Returns the current logged-in user (if any).
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end
    
    # Logs out the current user.
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

site-pedepizza/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

site-pedepizza/app/helpers/users_helper.rb
module UsersHelper
end

site-pedepizza/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pé de Pizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to "Sair", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

site-pedepizza/app/views/static_pages/home.html.erb
<header class="menu">
    <div class="itens-menu">
        <a class="menu-logo" href="#">
            <img src="assets/images/logo.jpeg">
        </a>	
        <nav class="menu-nav">
            <ul>
                <li><a href="#">Promoções</a></li>
                <li><a href="#">Cardápio</a></li>
                <li><a href="#">Quem Somos</a></li>
                <li><a href="#">Contato</a></li>
                <a class="peca-agora" href="#">Peça Agora</a>
            </ul>
        </nav>
    </div>
</header>

site-pedepizza/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, "E-mail" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password, "Senha" %>
    <%= form.password_field :password %>
  </div>
  
	  <div class="field">
    <%= form.label :password_confirmation, "Confirmar senha" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>
<% end %>

site-pedepizza/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

site-pedepizza/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

site-pedepizza/app/views/users/new.html.erb
<h1>Cadastre-se!</h1>

<%= render 'form', user: @user %>

site-pedepizza/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>